name: NmsTestPlugin
main: com.vanillage.nmstestplugin.NmsTestPlugin
version: 1.0.0-SNAPSHOT
api-version: '1.20'
description: A NMS test plugin.
# load: POSTWORLD
# dependencies: []
# load-after: []
# load-before: []
# has-open-classloader: false
# bootstrapper: io.papermc.testplugin.TestPluginBootstrap
# loader: io.papermc.testplugin.TestPluginLoader
folia-supported: true
# permissions: {}
